# Generated by Django 4.2.1 on 2023-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0002_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
